#+TITLE: Práctico Nro. 4.3: Excepciones
#+AUTHOR: Juan Jose Della Vecchia
#+STARTUP: overview

* Ejercicio 1:
Construya un programa que permita que transforme un string
a un número. Controle las situaciones de error usando excepciones.
#+begin_src python

#+end_src

* Ejercicio 2:
Escriba un programa que permita insertar, modificar y eliminar
elementos de una lista. Controle la situaciones de error usando
excepciones.
#+begin_src python

#+end_src

* Ejercicio 3:
Escriba un programa que permita que el usuario ingrese una
lista de elementos. El programa debe sumar los elementos numéricos
que se encuentran en la lista. Cuando el programa encuentra un elemento
que no es numérico dispara una excepción ValueError la cual
tiene un manejador que inserta el elemento que provocó la excepción
en una lista de elementos no numéricos.
#+begin_src python

#+end_src

* Ejercicio 4:
Escriba un programa que permita que el usuario cree un diccio-
nario. El programa permite: insertar, eliminar y modificar los elementos
del diccionario. Cuando se desea insertar un valor cuya clave ya existe el
programa dispara una excepción KeyError cuyo manejador pregunta al
usario si realmente desea modificar el valor. En caso afirmativo realiza
la modificación correspondiente. En caso negativo el programa no realiza
ninguna acción. El programa también debe manejar los errores por
intento de acceso al diccionarion y otros que puedan surgir utilizando
una clave incorrecta.
#+begin_src python

#+end_src

* Ejercicio 5:
Escriba un ejemplo que dispare una excepción, la controle y
muestre el uso de finally.
#+begin_src python

#+end_src
